import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    DATABASE_URL: z.string().url(),
    DIRECT_URL: z.string().url().optional(),
    AUTH_SECRET: z.string().min(32),
    AUTH_TRUST_HOST: z.coerce.boolean().default(false),
    WEBMASTER_EMAIL: z.string().email().optional(),
    WEBMASTER_PASSWORD: z.string().min(12).optional(),
    REDIS_URL: z.string().url(),
    S3_ENDPOINT: z.string().url(),
    S3_REGION: z.string().default("us-east-1"),
    S3_ACCESS_KEY: z.string().min(1),
    S3_SECRET_KEY: z.string().min(1),
    S3_BUCKET_UPLOADS: z.string().min(1),
    S3_BUCKET_EXPORTS: z.string().min(1),
    S3_BUCKET_BACKUPS: z.string().min(1),
    SMTP_HOST: z.string().min(1),
    SMTP_PORT: z.coerce.number().int().positive(),
    SMTP_USER: z.string().optional(),
    SMTP_PASS: z.string().optional(),
    SMTP_FROM: z.string().min(1),
    TURNSTILE_SECRET_KEY: z.string().min(1),
    WEB_PUSH_PRIVATE_KEY: z.string().min(1),
    WEB_PUSH_SUBJECT: z.string().min(1),
    LAN_MODE_ENABLED: z.coerce.boolean().default(false),
    LAN_DEFAULT_TENANT_SLUG: z.string().default("default"),
  },
  client: {
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: z.string().min(1),
    NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    DIRECT_URL: process.env.DIRECT_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_TRUST_HOST: process.env.AUTH_TRUST_HOST,
    WEBMASTER_EMAIL: process.env.WEBMASTER_EMAIL,
    WEBMASTER_PASSWORD: process.env.WEBMASTER_PASSWORD,
    REDIS_URL: process.env.REDIS_URL,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_REGION: process.env.S3_REGION,
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
    S3_SECRET_KEY: process.env.S3_SECRET_KEY,
    S3_BUCKET_UPLOADS: process.env.S3_BUCKET_UPLOADS,
    S3_BUCKET_EXPORTS: process.env.S3_BUCKET_EXPORTS,
    S3_BUCKET_BACKUPS: process.env.S3_BUCKET_BACKUPS,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_FROM: process.env.SMTP_FROM,
    TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
    WEB_PUSH_PRIVATE_KEY: process.env.WEB_PUSH_PRIVATE_KEY,
    WEB_PUSH_SUBJECT: process.env.WEB_PUSH_SUBJECT,
    LAN_MODE_ENABLED: process.env.LAN_MODE_ENABLED,
    LAN_DEFAULT_TENANT_SLUG: process.env.LAN_DEFAULT_TENANT_SLUG,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: process.env.NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  },
  skipValidation: process.env.SKIP_ENV_VALIDATION === "true",
  emptyStringAsUndefined: true,
});
